function tableOutput = importSampleFile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TIMESCAN4983 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  TIMESCAN4983 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  TimeScan4983 = importfile("C:\Users\graya\Box\2025 LBNL Research - Shared\In Situ Data\250630\TimeScan4983.txt", [7, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Jul-2025 10:23:57

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [7, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 36);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["TimeOfDay", "Times", "LoadCelllb", "Var4", "LoadCellN", "Var6", "LoadingStageum", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36"];
opts.SelectedVariableNames = ["TimeOfDay", "Times", "LoadCelllb", "LoadCellN", "LoadingStageum"];
opts.VariableTypes = ["datetime", "double", "double", "char", "double", "char", "double", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char", "char"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var4", "Var6", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var4", "Var6", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "TimeOfDay", "InputFormat", "HH:mm:ss", "DatetimeFormat", "preserveinput");

% Import the data
tableOutput = readtable(filename, opts);

end